name: Run ESPN Bot

on:
  schedule:
    - cron: '*/30 * * * *' # Runs every 30 minutes
  workflow_dispatch: # Allows manual trigger button

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Execute script
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          LEAGUE_ID: ${{ secrets.LEAGUE_ID }}
          LEAGUE_YEAR: ${{ secrets.LEAGUE_YEAR }}
          START_DATE: '2026-08-31'
          END_DATE: '2027-02-15'
          ESPN_S2: ${{ secrets.ESPN_S2 }}
          SWID: ${{ secrets.SWID }}
        run: python gamedaybot/espn/espn_bot.py init
